from tkinter import *
root=Tk()
root.title("Abhishek")
root.geometry("350x225+350+350")
lbl0=Label(root,text="Registration Form",bg="lightpink",font=("Arial","20","bold"))
lbl0.grid()
lbl=Label(root,text="Student name",font=("Arial","10","bold"))
lbl.grid()
ent=Entry(root,width=30,bg="aqua")
ent.grid(row=1,column=1)
lbl1=Label(root,text="Father's name",font=("Arial","10","bold"))
lbl1.grid()
ent1=Entry(root,width=30,bg="aqua")
ent1.grid(row=2,column=1)
lbl2=Label(root,text="Roll num",font=("Arial","10","bold"))
lbl2.grid()
ent2=Entry(root,width=30,bg="aqua")
ent2.grid(row=3,column=1)
lbl3=Label(root,text="DOB",font=("Arial","10","bold"))
lbl3.grid()
ent3=Entry(root,width=30,bg="aqua")
ent3.grid(row=4,column=1)
lbl4=Label(root,text="Branch name",font=("Arial","10","bold"))
lbl4.grid()
ent4=Entry(root,width=30,bg="aqua")
ent4.grid(row=5,column=1)
lbl5=Label(root,text="Adress",font=("Arial","10","bold"))
lbl5.grid()
ent5=Entry(root,width=30,bg="aqua")
ent5.grid(row=6,column=1)
def click():
   Messagebox.showinfo("title","Realy want to cancle")
btn1=Button(root,text="Cancle",bg="Red",command=click())
btn1.grid(row=7,column=0)
def display():
    Messagebox.showinfo("title","you have succefully Registered?")
btn=Button(root,text="submit",bg="lightblue",command=display())
btn.grid(row=7,column=1)
root.mainloop()
